package cn.com.ufgov.hainan.manage.module;

// Generated 2013-4-20 9:49:36 by Hibernate Tools 3.4.0.CR1

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/**
 * ManageMenu generated by hbm2java
 */
public class ManageMenu implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String uuid;
	private ManageCatalog manageCatalog;
	private String insertUserId;
	private Calendar insertTime;
	private String updateUserId;
	private Calendar updateTime;
	private String remark;
	private String name;
	private long serial;
	private Set<ManageLink> manageLinks = new HashSet<ManageLink>(0);

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public ManageCatalog getManageCatalog() {
		return this.manageCatalog;
	}

	public void setManageCatalog(ManageCatalog manageCatalog) {
		this.manageCatalog = manageCatalog;
	}

	public String getInsertUserId() {
		return this.insertUserId;
	}

	public void setInsertUserId(String insertUserId) {
		this.insertUserId = insertUserId;
	}

	public Calendar getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Calendar insertTime) {
		this.insertTime = insertTime;
	}

	public String getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Calendar getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Calendar updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getSerial() {
		return this.serial;
	}

	public void setSerial(long serial) {
		this.serial = serial;
	}

	public Set<ManageLink> getManageLinks() {
		return this.manageLinks;
	}

	public void setManageLinks(Set<ManageLink> manageLinks) {
		this.manageLinks = manageLinks;
	}

}
